"""Simulation configuration."""

PARKING_CAPACITY = 5
TOTAL_VEHICLES = 15

MIN_ARRIVAL_TIME = 1
MAX_ARRIVAL_TIME = 4

MIN_PARKING_TIME = 3
MAX_PARKING_TIME = 8

SHUTDOWN_POLL_INTERVAL_MS = 100
SHUTDOWN_DRAIN_WARNING_SECONDS = MAX_PARKING_TIME + 2
